domain: charmed-kubeflow.io

image: prod-comms.docker-registry.canonical.com/charmed-kubeflow.io

env:
  - name: SENTRY_DSN
    value: https://b365f83c60744cfea7b229836cad4eca@sentry.is.canonical.com//42

  - name: DISCOURSE_API_KEY
    secretKeyRef:
      key: charmhub-api-key
      name: discourse-api
      
  - name: DISCOURSE_API_USERNAME
    secretKeyRef:
      key: charmhub-api-username
      name: discourse-api

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'charmed-kubeflow.io' ) {
      rewrite ^ https://charmed-kubeflow.io$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
